version: '3'

name: spoons

services:
  # Development PostgreSQL Database
  dev-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DEV_DB_NAME}
    ports:
      - ${DEV_DB_HOST_PORT}:${DEV_DB_CONTAINER_PORT}
    volumes:
      - ./data/dev:/var/lib/postgresql/data

  # Test PostgreSQL Database
  test-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${TEST_DB_NAME}
    ports:
      - ${TEST_DB_HOST_PORT}:${TEST_DB_CONTAINER_PORT}
    volumes:
      - ./data/test:/var/lib/postgresql/data

  # Express API Service
  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file: .env
    ports:
      - ${API_PORT}:${API_PORT}
    depends_on:
      - dev-db
    environment:
      - DB_URL=postgres://${DB_USER}:${DB_PASSWORD}@dev-db:${DEV_DB_HOST_PORT}/${DEV_DB_NAME}
      - TEST_DB_URL=postgres://${DB_USER}:${DB_PASSWORD}@test-db:${TEST_DB_HOST_PORT}/${TEST_DB_NAME}
