version: '3'

name: spoons

services:
  # Development PostgreSQL Database
  dev-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DEV_DB_USER}
      POSTGRES_PASSWORD: ${DEV_DB_PASSWORD}
      POSTGRES_DB: ${DEV_DB_NAME}
    ports:
      - ${DEV_DB_HOST_PORT}:${DB_CONTAINER_PORT}
    volumes:
      - ./data/dev:/var/lib/postgresql/data

  # Test PostgreSQL Database
  test-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${TEST_DB_USER}
      POSTGRES_PASSWORD: ${TEST_DB_PASSWORD}
      POSTGRES_DB: ${TEST_DB_NAME}
    ports:
      - ${TEST_DB_HOST_PORT}:${DB_CONTAINER_PORT}
    volumes:
      - ./data/test:/var/lib/postgresql/data

  # Express API Service
  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file: .env
    ports:
      - ${API_PORT}:${API_PORT}
    depends_on:
      - dev-db
    environment:
      - DATABASE_URL=postgres://${DEV_DB_USER}:${DEV_DB_PASSWORD}@dev-postgres:${DB_CONTAINER_PORT}/${DEV_DB_NAME}
