version: '3'

name: spoons

services:
  # Redis cache
  cache:
    image: redis:7.2.3-alpine3.18
    restart: always
    ports:
      - ${REDIS_HOST_PORT}:${REDIS_CONTAINER_PORT}
    command: redis-server --save 60 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    volumes: 
      - ./data/cache:/var/lib/redis/data

  # Development PostgreSQL Database
  dev-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DEV_DB_NAME}
    ports:
      - ${DEV_DB_HOST_PORT}:${DEV_DB_CONTAINER_PORT}
    volumes:
      - ./data/dev:/var/lib/postgresql/dev/data
      - ./db:/db
      - ./db/db-populated.sql:/docker-entrypoint-initdb.d/db-populated.sql

  # Test PostgreSQL Database
  test-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${TEST_DB_NAME}
    ports:
      - ${TEST_DB_HOST_PORT}:${TEST_DB_CONTAINER_PORT}
    volumes:
      - ./data/test:/var/lib/postgresql/test/data
      - ./db:/db
      - ./db/db.sql:/docker-entrypoint-initdb.d/db.sql

  # Express API Service
  api:
    # container_name: spoons-api
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file: .env
    ports:
      - ${API_PORT}:${API_PORT}
    depends_on:
      - dev-db
      - cache
    environment:
      - DB_URL=postgres://${DB_USER}:${DB_PASSWORD}@dev-db/${DEV_DB_NAME}
      - TEST_DB_URL=postgres://${DB_USER}:${DB_PASSWORD}@test-db/${TEST_DB_NAME}
