Table users {
  user_id integer [primary key]
  first_name varchar
  last_name varchar
  created_at datetime
  updated_at datetime
}

Table user_identities {
  identity_id string
  user_id integer [ref: > users.user_id]
  provider enum_provider_type
  status enum_user_identities_status
  created_at datetime
  updated_at datetime

  Indexes {
    (user_id, provider) [unique]
  }
}

Enum enum_provider_type {
  google
  facebook
}

Enum enum_user_identities_status {
  active
  inactive
}

Table user_accounts {
  user_id integer [primary key]
  email varchar
  password varchar
  status enum_user_account_status 
  created_at datetime
  updated_at datetime
}

Enum enum_user_account_status {
  active
  inactive
  pending
}

Ref: user_accounts.user_id - users.user_id

Table otp {
  otp_id integer [primary key]
  user_id integer [ref: > user_accounts.user_id]
  type  enum_otp_type
  password varchar
  expires_at datetime

  Indexes {
    (user_id, type) [unique]
  }
}

Enum enum_otp_type {
  password
  verify
}

Table roles {
  role_id integer [primary key]
  name varchar [unique]
}

Table user_roles {
  user_id integer [ref: > users.user_id]
  role_id integer [ref: > roles.role_id]
  created_at datetime
  updated_at datetime

  Indexes {
    (user_id, role_id) [unique]
  }
}

Table permissions {
  permission_id integer [primary key]
  name varchar [unique]
}

Table role_permissions {
  role_id integer [ref: > roles.role_id]
  permission_id integer [ref: > permissions.permission_id]
  created_at datetime
  updated_at datetime

  Indexes {
    (role_id, permission_id) [unique]
  }
}